<?php

namespace AppBundle\Repository;

/**
 * employeePositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeePositionRepository extends \Doctrine\ORM\EntityRepository
{
}
