<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Employee;

/**
 * WorkOffDaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkOffDaysRepository extends \Doctrine\ORM\EntityRepository
{
    public function isCheckedDaysValid(Employee $employee, $lastCheck)
    {
        $query = $this->createQueryBuilder('wod')
            ->where('wod.employee = :name')
            ->andWhere('wod.isChecked <> true')
            ->andWhere('wod.date < :last_check')
            ->setParameters(['name' => $employee, 'last_check' => $lastCheck])->getFirstResult();

        // TODO: Continue DaysOff Checking
            //->getQuery();
    }
}
